version: '3'
services:
  api:
    command: yarn watch
    build: .
    environment:
      - JWT_KEY=
      - DB_URI=
      - NODE_ENV=
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
