version: '3'
services:
  api:
    command: npm run watch
    build: .
    environment:
      - JWT_KEY=test-key
      - DB_URI=mongodb://mongodb:27017/api
      - NODE_ENV=development
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo